<?php

namespace CrowdLuv\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FollowerLuvsTalentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowerLuvsTalentRepository extends EntityRepository
{
}
