<?php

namespace CrowdLuv\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TalentLandingPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalentLandingPageRepository extends EntityRepository
{
}
